name: personal_finance
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^2.22.0
  firebase_auth: ^4.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/images/onboarding.png
    - assets/images/login.png
    - assets/images/Rectangle 1.png
    - assets/images/specular.png
    - assets/images/home_page_top.png
    - assets/images/headerBell.png
    - assets/images/Icon.png
    - assets/images/down_arrow.png
    - assets/images/up_arrow.png
    - assets/images/upwork_image.png
    - assets/images/account_icon.png
    - assets/images/home_icon.png
    - assets/images/personal_icon.png
    - assets/images/person_icon.png
    - assets/images/statistics_icon.png
    - assets/images/paypal_icon.png
    - assets/images/youtube_icon.png
    - assets/images/right_shape.png
    - assets/images/logo_paypal.png
    - assets/images/dollar.png
    - assets/images/send.png
    - assets/images/plus.png
    - assets/images/qr_code.png
    - assets/images/bank.png
