// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
// import 'firebase_options.dart';
// /// // ...
// await Firebase.initializeApp(
//   options: DefaultFirebaseOptions.currentPlatform,
// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macOS - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIBIoc3zaqxgXIGMKP6MtKk40NsnM_V9w',
    appId: '1:487138648423:web:9893c43bcc3d71d4cc4fc2',
    messagingSenderId: '487138648423',
    projectId: 'icsi401',
    authDomain: 'icsi401.firebaseapp.com',
    storageBucket: 'icsi401.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYZt0YMdOWR6asvbhv_6f9AO8UcFxV42w',
    appId: '1:487138648423:android:144532d952cf6e80cc4fc2',
    messagingSenderId: '487138648423',
    projectId: 'icsi401',
    storageBucket: 'icsi401.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1JA2-VycOgYqIeJGTEK4m5asapdbYTu0',
    appId: '1:487138648423:ios:12a81b0c80933829cc4fc2',
    messagingSenderId: '487138648423',
    projectId: 'icsi401',
    storageBucket: 'icsi401.appspot.com',
    iosBundleId: 'com.example.personalFinance',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1JA2-VycOgYqIeJGTEK4m5asapdbYTu0',
    appId: '1:487138648423:ios:da511c90a517bbdecc4fc2',
    messagingSenderId: '487138648423',
    projectId: 'icsi401',
    storageBucket: 'icsi401.appspot.com',
    iosBundleId: 'com.example.personalFinance.RunnerTests',
  );
}
